server:
  port: 8899
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/weather?serverTimezone=UTC&?useUnicode=true&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    data-password: root
    data-username: 123456

  thymeleaf:
    cache: false
    suffix: .ftl
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/

